### PR TITLE
Update platform.txt

### PR DESCRIPTION
**Pull request by zdjurisic**
Updated compiler.path and patterns to what is appropriate for compiler supplied with Arduino IDE 1.8.2. Compilation would update those on it's own during compilation anyway; this update just removes warning messages.

### CODE REVIEW

**Comment by psychogenic** [comment]
Hi,
Not certain if this project is still alive (I use it a lot!), but I just made another change to get a library to compile successfully (and maybe make other things possible, too)

Replacing:
compiler.cpp.flags=-c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD
With
compiler.cpp.flags=-c -g -Os {compiler.warning_flags} -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD

as in my standard arduino platform file, seems to work well and give some newer/useful CPP stuff.

**Comment by karlbackstrom** [comment]
Hi, it is still alive (somewhat), so please send a pull-request and it will most likely be added.

**Comment by psychogenic** [comment]
Hi, thanks for the answer.
Ok, I'll do that.
I really do use this port for many of my personal and professional projects--the xmegas have a lot of sweet features.  I'd really like to see xmegaduino thrive or at stay healthy, so two questions:
 * what's the reason it's only somewhat alive?; and
 * do you need anything worked on to keep it going?
Thanks,
P

**Comment by karlbackstrom** [comment]
Hi,

Great to see that it is used.

Mainly the reason for the somewhat alive is time constrains.

One area I would love to get some improvement is to make Xmegaduino into a supported board library in the board manager.
I have started the work here:
https://github.com/Xmegaduino/Xmegaduino/commit/999bee116eee47e4e8fd922c8cf053e2e3f88b1b

Best regards,
Karl

**Pull request merged**
