### PR TITLE
Multi-port SPI library patch

### PR DESCRIPTION
**Pull request by psychogenic**
These changes to the standard SPI lib leave existing functionality as-is but allow for expanded use of SPI on platforms that have multiple ports available.  The SPI.h header includes full documentation, but in essence there are two new ways to use SPI for xmega:

1) Dynamically adjusting the SPI global instance to use another port.  This is the best option for use with 3rd party code--I've tested, for example, using the Dataflash library on SPID by simply:

  // creating a config
  SPISettings myPortD(&SPID, SS1, MOSI1, MISO1, SCK1);
  // assigning it to the global SPI
  SPI.setConfiguration(myPortD);

prior to the SPI.begin() call.  Without modifications, the Dataflash library code (which used SPI.methods() as well as SPSR/SPCR) just worked.

You can "hot swap" between ports, by calling setConfiguration() at any time (as long as begin() was called once per config/port).

2) Using additional instances.  When using SPI directly, you can instantiate another SPIClass object and use that, e.g.

  // create an "SPI2" for the D port SPI
  SPI_DECLARE(SPI2, SPID, SS1, MOSI1, MISO1, SCK1);

  // use SPIClass API:
  SPI2.begin();
  SPI2.transfer(0xFF); 

I'd appreciate feedback and eventual inclusion in the main trunk. 

Regards,
Pat Deegan
http://flyingcarsandstuff.com/

### CODE REVIEW

**Comment by karlbackstrom** [comment]
Sorry for the late reply.

Thank you for the pull request, looks promising. Will do some testing on it this week and if everything looks good, merge it into the main project.

**Comment by psychogenic** [comment]
Hey, no worries about the reply--just glad you got back to me :)

Cool about the testing.  I'd really like this to be included, if you hit any snags or think the API should be changed in some way, let me know and I'll see what I can do.

Cheers,
PatD

**Comment by karlbackstrom** [comment]
I had some time to test this, but I have a problem.
When I added this code to the CardInfo.ino example from SD library I get the following error:
CardInfo.ino:29:1: error: 'SPI' does not name a type

(This is the code I added to test)
SPISettings myPortD(&SPID, 6, 11, 12, 13);
SPI.setConfiguration(myPortD);

**Comment by karlbackstrom** [comment]
Sorry, my mistake. Added it at wrong place.

**Comment by karlbackstrom** [comment]
Found a problem, while merging the latest Arduino 1.6.0, it seems that SPISettings is already defined in Sd2Card.cpp:

---

#else // USE_SPI_LIB
  switch (sckRateID) {
    case 0:  settings = SPISettings(25000000, MSBFIRST, SPI_MODE0); break;
    case 1:  settings = SPISettings(4000000, MSBFIRST, SPI_MODE0); break;
    case 2:  settings = SPISettings(2000000, MSBFIRST, SPI_MODE0); break;
    case 3:  settings = SPISettings(1000000, MSBFIRST, SPI_MODE0); break;
    case 4:  settings = SPISettings(500000, MSBFIRST, SPI_MODE0); break;
    case 5:  settings = SPISettings(250000, MSBFIRST, SPI_MODE0); break;
    default: settings = SPISettings(125000, MSBFIRST, SPI_MODE0);
  }
#endif // USE_SPI_LIB

---

Would you mind sending a new pull request with a name change?

**Comment by psychogenic** [comment]
Will do so... just need to think of something suitable.  Any aversion to namespaces?

**Comment by karlbackstrom** [comment]
SPIPortSettings?

On 20 November 2014 06:41, psychogenic notifications@github.com wrote:

> Will do so... just need to think of something suitable. Any aversion to
> namespaces?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akafugu/Xmegaduino/pull/34#issuecomment-63719127.

## 

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Pull request merged**
